/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import type { Recipe } from '@pmndrs/chef';
import {
  DEFAULT_ASSETS_BASE,
  fetchRecipesIndex,
  fetchRecipeByFileName,
} from './recipes.js';
import type { VariantId } from './types.js';

/**
 * Directory inside scaffolded projects where SDK package tarballs are stored.
 * Preserves the monorepo's subdirectory hierarchy so that internal `file:`
 * references between packages (e.g., core → glxf) resolve correctly.
 */
export const SDK_PACKAGES_DIR = '.sdk-packages';

/**
 * Default CDN URL for the canary SDK bundle.
 */
export const DEFAULT_BUNDLE_URL =
  'https://d1erq8v22udnml.cloudfront.net/sdk-bundle';

/**
 * Manifest file format for SDK bundles.
 * Generated by scripts/build-bundle.sh, consumed by BundleSource.
 */
export interface BundleManifest {
  schemaVersion: number;
  sdkVersion: string;
  packages: Record<string, string>;
}

/**
 * Abstraction over where SDK recipes and packages come from.
 * NpmSource fetches from jsDelivr CDN; BundleSource fetches from a remote
 * bundle URL.
 */
export interface ResolvedSource {
  /** One-time setup (e.g., validate remote bundle manifest) */
  prepare(): Promise<void>;

  /** Fetch the recipes index.json */
  fetchIndex(): Promise<{ id: VariantId; name: string; recipe: string }[]>;

  /** Fetch a recipe by its file name */
  fetchRecipe(fileName: string): Promise<Recipe>;

  /**
   * Return the install specifier for an @iwsdk/* package.
   * NpmSource returns undefined (npm resolves from registry);
   * BundleSource returns a file: path pointing at .sdk-packages/.
   */
  getPackageInstallSpec(name: string): string | undefined;

  /**
   * Return every @iwsdk/* package install spec known by this source.
   * BundleSource uses this to keep transitive IWSDK dependencies local instead
   * of falling back to the registry during npm install.
   */
  getPackageInstallSpecs(): Record<string, string>;

  /**
   * Download SDK package tarballs into a local directory.
   * NpmSource is a no-op; BundleSource fetches tgz files from the
   * remote bundle and writes them preserving the subdirectory hierarchy.
   */
  downloadPackages(destDir: string): Promise<void>;

  /**
   * Resolve relative asset URLs in a recipe to absolute URLs.
   * Returns a new recipe object (no mutation).
   */
  resolveRecipeUrls(recipe: Recipe): Recipe;

  /** Whether this source uses bundle mode */
  isBundleMode: boolean;

  /** Cleanup temp resources */
  cleanup(): Promise<void>;
}

/**
 * Prepend a base URL to relative `url` edits in a recipe.
 * Absolute URLs pass through unchanged (backwards compatible).
 * Returns a new recipe object (no mutation).
 */
function prependBaseUrl(recipe: Recipe, base: string): Recipe {
  const edits = recipe.edits;
  if (!edits) {
    return recipe;
  }

  const baseWithSlash = base.endsWith('/') ? base : base + '/';
  const newEdits: Record<string, any> = {};
  let changed = false;

  for (const [key, value] of Object.entries(edits)) {
    if (
      value &&
      typeof value === 'object' &&
      'url' in value &&
      typeof (value as any).url === 'string'
    ) {
      const url = (value as any).url as string;
      if (!URL.canParse(url)) {
        // Relative URL — prepend base
        newEdits[key] = { ...value, url: new URL(url, baseWithSlash).href };
        changed = true;
      } else {
        newEdits[key] = value;
      }
    } else {
      newEdits[key] = value;
    }
  }

  if (!changed) {
    return recipe;
  }
  return { ...recipe, edits: newEdits };
}

/**
 * Default source: fetches recipes and packages from jsDelivr CDN / npm registry.
 */
export class NpmSource implements ResolvedSource {
  isBundleMode = false;

  async prepare(): Promise<void> {
    // no-op
  }

  async fetchIndex(): Promise<
    { id: VariantId; name: string; recipe: string }[]
  > {
    return fetchRecipesIndex();
  }

  async fetchRecipe(fileName: string): Promise<Recipe> {
    return fetchRecipeByFileName(fileName);
  }

  getPackageInstallSpec(_name: string): string | undefined {
    return undefined; // npm resolves from registry using version in recipe
  }

  getPackageInstallSpecs(): Record<string, string> {
    return {};
  }

  async downloadPackages(_destDir: string): Promise<void> {
    // no-op — npm resolves packages from the registry
  }

  resolveRecipeUrls(recipe: Recipe): Recipe {
    const base = DEFAULT_ASSETS_BASE.endsWith('/')
      ? DEFAULT_ASSETS_BASE
      : DEFAULT_ASSETS_BASE + '/';
    return prependBaseUrl(recipe, base);
  }

  async cleanup(): Promise<void> {
    // no-op
  }
}

/**
 * Bundle source: fetches recipes and packages from a remote HTTP(S) bundle URL.
 * Resolves @iwsdk/* packages to local file: paths after downloading tarballs.
 */
export class BundleSource implements ResolvedSource {
  isBundleMode = true;

  private baseUrl: string;
  private manifest: BundleManifest | null = null;

  constructor(bundleUrl: string) {
    if (!bundleUrl.startsWith('http://') && !bundleUrl.startsWith('https://')) {
      throw new Error(
        `Bundle URL must be an HTTP or HTTPS URL. Got: "${bundleUrl}"`,
      );
    }
    this.baseUrl = bundleUrl;
  }

  async prepare(): Promise<void> {
    const manifestContent = await this.readContent('bundle.json');
    this.manifest = JSON.parse(manifestContent) as BundleManifest;

    if (this.manifest.schemaVersion !== 1) {
      throw new Error(
        `Unsupported bundle schema version: ${this.manifest.schemaVersion}. ` +
          'Please update your CLI or use a compatible bundle.',
      );
    }
  }

  async fetchIndex(): Promise<
    { id: VariantId; name: string; recipe: string }[]
  > {
    const content = await this.readContent('recipes/index.json');
    return JSON.parse(content);
  }

  async fetchRecipe(fileName: string): Promise<Recipe> {
    const content = await this.readContent(`recipes/${fileName}`);
    return JSON.parse(content);
  }

  getPackageInstallSpec(name: string): string | undefined {
    if (!this.manifest) {
      return undefined;
    }
    const tgzRelPath = this.manifest.packages[name];
    if (!tgzRelPath) {
      return undefined;
    }
    return `file:${SDK_PACKAGES_DIR}/${this.manifestSubPath(tgzRelPath)}`;
  }

  getPackageInstallSpecs(): Record<string, string> {
    if (!this.manifest) {
      return {};
    }
    return Object.fromEntries(
      Object.entries(this.manifest.packages).map(([name, tgzRelPath]) => [
        name,
        `file:${SDK_PACKAGES_DIR}/${this.manifestSubPath(tgzRelPath)}`,
      ]),
    );
  }

  async downloadPackages(destDir: string): Promise<void> {
    if (!this.manifest) {
      throw new Error(
        'BundleSource.prepare() must be called before downloadPackages()',
      );
    }

    const { mkdir, writeFile } = await import('fs/promises');
    const { dirname, join } = await import('path');

    for (const [, relPath] of Object.entries(this.manifest.packages)) {
      const subPath = this.manifestSubPath(relPath);
      const destFile = join(destDir, subPath);
      await mkdir(dirname(destFile), { recursive: true });

      const url = this.resolveUrl(relPath);
      const resp = await fetch(url);
      if (!resp.ok) {
        throw new Error(`HTTP ${resp.status} fetching ${url}`);
      }
      const buffer = Buffer.from(await resp.arrayBuffer());
      await writeFile(destFile, buffer);
    }
  }

  resolveRecipeUrls(recipe: Recipe): Recipe {
    return prependBaseUrl(recipe, this.baseUrl);
  }

  async cleanup(): Promise<void> {
    // no-op (no temp dir)
  }

  /**
   * Read content from the remote bundle via fetch.
   */
  private async readContent(relativePath: string): Promise<string> {
    const url = this.resolveUrl(relativePath);
    const resp = await fetch(url);
    if (!resp.ok) {
      throw new Error(`HTTP ${resp.status} for ${url}`);
    }
    return resp.text();
  }

  /**
   * Resolve a relative path against the remote base URL.
   */
  private resolveUrl(relativePath: string): string {
    const base = this.baseUrl.endsWith('/') ? this.baseUrl : this.baseUrl + '/';
    return new URL(relativePath, base).toString();
  }

  /**
   * Strip the leading `packages/` prefix from a manifest path.
   * e.g. `packages/core/iwsdk-core.tgz` → `core/iwsdk-core.tgz`
   */
  private manifestSubPath(relPath: string): string {
    return relPath.replace(/^packages\//, '');
  }
}

/**
 * Factory: create the appropriate source based on the --canary flag.
 *
 * - `undefined` / `false` → NpmSource (default)
 * - `true` (bare --canary)  → BundleSource with DEFAULT_BUNDLE_URL
 * - `string`                → BundleSource with the provided URL
 */
export function resolveSource(canaryFlag?: string | boolean): ResolvedSource {
  if (!canaryFlag) {
    return new NpmSource();
  }
  const url = typeof canaryFlag === 'string' ? canaryFlag : DEFAULT_BUNDLE_URL;
  return new BundleSource(url);
}
